export const GET_CHART_DATA_LOADING="GET_CHART_DATA_LOADING";
export const GET_HEADER_DATA_SUCCESS="GET_HEADER_DATA_SUCCESS";
export const GET_HEADER_DATA_ERROR="GET_HEADER_DATA_ERROR";
export const GET_PIE_DATA_SUCCESS="GET_PIE_DATA_SUCCESS";

export const GET_LINE_DATA_SUCCESS="GET_LINE_DATA_SUCCESS";

export const GET_BAR_DATA_SUCCESS="GET_BAR_DATA_SUCCESS";
